CREATE EXTENSION oracle_fdw;
CREATE SERVER wpd FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//HCOR-BD01.HCOR.LOCAL/PROD');
GRANT USAGE ON FOREIGN SERVER wpd TO cc;
CREATE USER MAPPING FOR cc SERVER wpd OPTIONS (user 'financeiro', password 'financeiro');

DROP FOREIGN TABLE IF EXISTS produto;
CREATE FOREIGN TABLE produto (
  setor VARCHAR(70) OPTIONS (key 'true') NOT NULL,
  codigo CHAR(7) OPTIONS (key 'true') NOT NULL,
  descricao VARCHAR(70) NOT NULL,
  estoque VARCHAR(70) NOT NULL,
  bloqueado CHAR(1)
) SERVER wpd
OPTIONS (table '(SELECT SETOR.DESCRICAO AS SETOR, PRODUTO.CODIGO, PRODUTO.DESCRICAO, ESTOQUE.EST_ATU AS ESTOQUE, PRODUTO.BLOQUEADO FROM ADMWPD.ESESTCAD ESTOQUE
                   INNER JOIN ADMWPD.FASETCAD SETOR ON ESTOQUE.COD_SET = SETOR.COD_SET
                   INNER JOIN ADMWPD.FAPRDCAD PRODUTO ON ESTOQUE.COD_PRD = PRODUTO.CODIGO WHERE PRODUTO.BLOQUEADO <> ''S'' ORDER BY PRODUTO.DESCRICAO)', readonly 'true');

