CREATE EXTENSION oracle_fdw;
CREATE SERVER wpd FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '//HCOR-BD01.HCOR.LOCAL/PROD');
GRANT USAGE ON FOREIGN SERVER wpd TO cc;
CREATE USER MAPPING FOR cc SERVER wpd OPTIONS (user 'financeiro', password 'financeiro')

DROP FOREIGN TABLE IF EXISTS produto;
CREATE FOREIGN TABLE produto (
  id VARCHAR(7) OPTIONS (key 'true') NOT NULL,
  descricao VARCHAR(70) NOT NULL,
  estoque NUMERIC NOT NULL
) SERVER wpd
OPTIONS (table '(SELECT PRODUTO.CODIGO, PRODUTO.DESCRICAO, SUM(NVL(ESTOQUE.EST_ATU, 0))
FROM ADMWPD.FAPRDCAD PRODUTO
  LEFT JOIN ADMWPD.ESESTCAD ESTOQUE ON ESTOQUE.COD_PRD = PRODUTO.CODIGO
WHERE PRODUTO.BLOQUEADO <> ''S''
GROUP BY PRODUTO.CODIGO, PRODUTO.DESCRICAO)', readonly 'true');